language: node_js
node_js:
  - "0.10"
install:
  - npm install
  - npm install -g bower grunt-cli
before_script:
  - sed s#"2.1.3 - 3.99"#"^2.1.3"#g -i bower.json
  - bower install
script:
  - grunt build --verbose
  - sed s#"\^2.1.3"#"^3"#g -i bower.json
  - bower install
  - grunt test --verbose
